# Hacker Rank  - Numpy problem

### Problem 01

#### Task

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

#### Input Format

A single line containing the space-separated integers.

#### Constraints

** 1<= n <= 3 **

#### Output Format

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

In [8]:
import numpy as np
ip_vals = input().rsplit(" ")
ip_vals = [int(val) for val in ip_vals]
ndims = tuple(ip_vals)


print(np.zeros(ndims, dtype='int32'))
print(np.ones(ndims, dtype='int32'))

2 2 2 2
[[[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]]
[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]


### Lessons

- use tuples while initiaizing np arrays
- list comprehension is nice way to shorten the code and impress people

### Problem 02

#### Task

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

#### Input Format

A single line of input containing space separated numbers.

#### Output Format

Print the reverse NumPy array with type float.

In [9]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    array1 = [float(x) for x in arr]
    np_array = numpy.array(array1[::-1], dtype='float')
    return np_array


arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1.1 2.2
[2.2 1.1]


#### Task

You are given two integer arrays,  and  of dimensions X.
Your task is to perform the following operations:

Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )
#### Input Format

The first line contains two space separated integers,  and .
The next  lines contains  space separated integers of array .
The following  lines contains  space separated integers of array .

#### Output Format

Print the result of each operation in the given order under Task.

Sample Input

In [10]:
import numpy as np

dims = input().strip().split(' ')
rows, cols  = [int(x) for x in dims]

a1 = []
for r in range(rows):
    arr = input().strip().split(' ')
    v1 = np.array([int(x) for x in arr])
    a1.append(v1)

b1 = []
for r in range(rows):
    arr = input().strip().split(' ')
    v1 = np.array([int(x) for x in arr])
    b1.append(v1)

a1 = np.vstack(a1)
b1 = np.vstack(b1)

print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 // b1)
print(a1 % b1)
print(a1 ** b1)

1 3
1 2 3
2 3 4
[[3 5 7]]
[[-1 -1 -1]]
[[ 2  6 12]]
[[0 0 0]]
[[1 2 3]]
[[ 1  8 81]]
