## Complete Python NumPy Tutorial (Creating Arrays, Indexing, Math, Statistics, Reshaping)


- https://www.youtube.com/watch?v=GB9ByFAIAH4

#### Keith Galli

- numpy is a multidimensionl array libray


#### 1 - Diff between numpy and list?

- numpy is superfast than lists
    - numpy uses fixed type


#### 2 - Why numpy is faster than list?
    - numpy uses a fixed type for one array
        - elements of numpy take fixed size and stored in contigous memory        
        - accessing them is faster, it make use of SIMD and cache
        
    - elements of list 
     - while list is a genercic conotainer
        - generic container
            - each elemets has
                - size
                - reference count
                - Object type
                - Object Value
     - numpy
         - uses less bytes and stored contigously
             - less bytes to read
             - SIMD and cache effective
         - while doing opration we don't have to do type check each time
         - numpy can use efficent data types (like bytes and all)

#### 3 - Application of Numpy
    - maths (matlab replacement)
    - backend of many applications (panda, image processing)
    - machine learning
    - matplot lib
    
#### 4 - Lists vs Numpy
    - Insertion, Deletion, Append, Concat all can be done in both
    - in numpy we can do element wise arithmetic (not possible in list)

In [205]:
l1 = [ 1, 2 , 4]
l2 = [ 3, 4,  5]

In [206]:
l1 + l2

[1, 2, 4, 3, 4, 5]

In [207]:
import numpy as np

## The basics 

### inspect an array

In [208]:
a_normal = np.array([1 , 2, 3])
a_int16  = np.array([1,  2, 3], dtype = 'int16')

In [209]:
print(a_normal, a_int16)

[1 2 3] [1 2 3]


In [210]:
b = np.array([[9.0, 8.0, 7.5], [6.1, 5.3, 2.2]])

In [211]:
print(b)

[[9.  8.  7.5]
 [6.1 5.3 2.2]]


####  Get Dimension

In [212]:
print(a_normal.ndim, a_int16.ndim, b.ndim)

1 1 2


#### Get shape

In [213]:
print(a_normal.shape, a_int16.shape, b.shape)

(3,) (3,) (2, 3)


#### Get type

In [214]:
print(a_normal.dtype, a_int16.dtype, b.dtype)

int32 int16 float64


####  Get total elements

In [215]:
print(a_normal.size, a_int16.size, b.size)

3 3 6


In [216]:
len(a_normal)

3

####  Get elemnt size and total size
    - what about the book keepoing for a, b (saying they are float, int)?

In [217]:
print(a_normal.itemsize, a_int16.itemsize, b.itemsize)

4 2 8


In [218]:
print(a_normal.size * a_normal.itemsize, a_int16.size* a_int16.itemsize, b.size * b.itemsize)

12 6 48


In [219]:
print(a_normal.nbytes, a_int16.nbytes, b.nbytes)

12 6 48


## Accessing/Changing specific elements, rows, columns

In [220]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9 , 10, 11, 12, 13, 14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


####  Get a specific element

In [221]:
a [1, 5]

13

####  you can also use the negative notation like list with numpy arrays

In [222]:
a[-1, -2]

13

#### Get a specific row or coloumn, we can use the slicing sililiar to lists

In [223]:
print(a[1, :])
print(a[:, 2])

print(a[1, :].shape)
print(a[:, 2].shape)

[ 8  9 10 11 12 13 14]
[ 3 10]
(7,)
(2,)


#### Getting a little more fancy, indexing

In [224]:
a_list = [1, 2, 3, 4, 5, 6, 7]

In [225]:
a_list[1:5:2]

[2, 4]

In [226]:
print(a[1, 1:5:2])
print(a[1:5:2, 2])

[ 9 11]
[10]


In [227]:
print(a[:, 3:5])

[[ 4  5]
 [11 12]]


In [228]:
c = np.array([[[1, 2],
               [3, 4]],
             
              [[5, 6],
               [7, 8]]
             ])

print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [229]:
# get first element of every rows

c[:,:, 0]

array([[1, 3],
       [5, 7]])

In [230]:
#get second row of every matrix

c[:, 1, :]

array([[3, 4],
       [7, 8]])

#### Once you can access properly, you can give the right sized input to update
    - always the access is row first column second
    - the assigned element should be of right size or single element

In [231]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9 , 10, 11, 12, 13, 14]])
print(a)

#set the third column

a[:, 2] = [9,9]
print(a)

#set 4th and 5 th coumn
a[:, 3:5] = [[9,10], [9, 10]]
print(a)

a[:, 3:5] = 12
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  9  4  5  6  7]
 [ 8  9  9 11 12 13 14]]
[[ 1  2  9  9 10  6  7]
 [ 8  9  9  9 10 13 14]]
[[ 1  2  9 12 12  6  7]
 [ 8  9  9 12 12 13 14]]


In [232]:
c = np.array([[[1, 2],
               [3, 4]],
             
              [[5, 6],
               [7, 8]]
             ])

print(c)


#set first element of all arrays

c[:, :, 0] = 0

print(c)

#set the second row in 13, 14, 17, 18
c[:, 1, :] = [[13, 14],
              [17, 18]]

print(c)


#set the second coumn in 32, 44, 36, 48
c[:, :, 1] = [[32, 44],
              [36, 48]]

print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[0 2]
  [0 4]]

 [[0 6]
  [0 8]]]
[[[ 0  2]
  [13 14]]

 [[ 0  6]
  [17 18]]]
[[[ 0 32]
  [13 44]]

 [[ 0 36]
  [17 48]]]


#### What is the exact order in which things are getting filled?
    - scan rows first seems to be the principle

## Initializing different types of arrays

In [233]:
#All zero matrix
test = np.zeros((2, 3))
print(test, test.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [234]:
#All 1s matrix

test = np.ones((2, 3), dtype='int16')
print(test, test.shape, test.dtype)

[[1 1 1]
 [1 1 1]] (2, 3) int16


In [235]:
#Initialize a matirx with any number

test1 = np.full((2, 3), 255, dtype='int16')
print(test1, test1.shape, test1.dtype)

[[255 255 255]
 [255 255 255]] (2, 3) int16


In [236]:
test2 = np.full_like(test1, 256, dtype='int16')
print(test2, test2.shape, test2.dtype)

[[256 256 256]
 [256 256 256]] (2, 3) int16


In [237]:
#Randome decimal number

rand1 = np.random.rand(2, 5)
print(rand1)


rand1 = np.random.random_sample(test2.shape)
print(rand1)

[[0.91062352 0.07698418 0.9762417  0.24125753 0.73964305]
 [0.8377246  0.14972627 0.85870154 0.48467715 0.66279828]]
[[0.74654615 0.47027222 0.90567658]
 [0.670364   0.5998881  0.8928849 ]]


In [238]:
#randome integer values with controlled range

rand1 = np.random.randint(7, size=(2, 5))
print(rand1)


rand1 = np.random.randint(-4, 5, size=(2, 5))
print(rand1)

[[5 3 0 3 5]
 [4 4 1 1 1]]
[[-3 -4  0 -1 -2]
 [ 1  1 -4 -1  2]]


In [239]:
#The identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [240]:
# repeat the elements in an array

arr = np.array([[1, 2, 3]])
r1  = np.repeat(arr, 3, axis=0)
r2  = np.repeat(arr, 3, axis=1)

print(arr)
print(r1)
print(r2)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


## Copying confusions,

### normal, shallow or deep ?
    - https://www.afternerd.com/blog/python-copy-list/

In [241]:
import copy

list1 = ['dog', 3, 5]
list2 = [list1, 2, 4]

print('-'*50)
print("list1: ", list1, "\nlist2: ", list2)

#trying 
list1 = ['dog', 3, 5]
list2 = [list1, 2, 4]

list3 = list2

list3.append('cat3')
list2.append('cat2')
list1.append('cat1')

print('-'*50)
print("list1: ", list1, "\nlist2: ", list2, "\nlist3: ", list3)

#trying shallow copy
list1 = ['dog', 3, 5]
list2 = [list1, 2, 4]

list3 = list2.copy()

list3.append('cat3')
list2.append('cat2')
list1.append('cat1')

print('-'*50)
print("list1: ", list1, "\nlist2: ", list2, "\nlist3: ", list3,)

#trying shallow copy using slicing
list1 = ['dog', 3, 5]
list2 = [list1, 2, 4]

list3 = list2[:]

list3.append('cat3')
list2.append('cat2')
list1.append('cat1')

print('-'*50)
print("list1: ", list1, "\nlist2: ", list2, "\nlist3: ", list3)

#trying deep copy
list1 = ['dog', 3, 5]
list2 = [list1, 2, 4]

list3 = copy.deepcopy(list2)

list3.append('cat3')
list2.append('cat2')
list1.append('cat1')

print('-'*50)
print("list1: ", list1, "\nlist2: ", list2, "\nlist3: ", list3)

--------------------------------------------------
list1:  ['dog', 3, 5] 
list2:  [['dog', 3, 5], 2, 4]
--------------------------------------------------
list1:  ['dog', 3, 5, 'cat1'] 
list2:  [['dog', 3, 5, 'cat1'], 2, 4, 'cat3', 'cat2'] 
list3:  [['dog', 3, 5, 'cat1'], 2, 4, 'cat3', 'cat2']
--------------------------------------------------
list1:  ['dog', 3, 5, 'cat1'] 
list2:  [['dog', 3, 5, 'cat1'], 2, 4, 'cat2'] 
list3:  [['dog', 3, 5, 'cat1'], 2, 4, 'cat3']
--------------------------------------------------
list1:  ['dog', 3, 5, 'cat1'] 
list2:  [['dog', 3, 5, 'cat1'], 2, 4, 'cat2'] 
list3:  [['dog', 3, 5, 'cat1'], 2, 4, 'cat3']
--------------------------------------------------
list1:  ['dog', 3, 5, 'cat1'] 
list2:  [['dog', 3, 5, 'cat1'], 2, 4, 'cat2'] 
list3:  [['dog', 3, 5], 2, 4, 'cat3']


## Mathematics

- element wise operation
- vector operations



In [242]:
a = np.array([1, 2, 3, 4])
print(a, a.dtype)

[1 2 3 4] int32


In [243]:
print(a + 5)
print(a - 5)
print(a / 5)
print(a // 5)
print(a * 5)
print(a ** 2)

[6 7 8 9]
[-4 -3 -2 -1]
[0.2 0.4 0.6 0.8]
[0 0 0 0]
[ 5 10 15 20]
[ 1  4  9 16]


In [244]:
b = np.array([ 6, 7, 8, 9])

In [245]:
print(a + b)
print(a - b)
print(a / b)
print(a // b)
print(a * b)
print(a ** b)

[ 7  9 11 13]
[-5 -5 -5 -5]
[0.16666667 0.28571429 0.375      0.44444444]
[0 0 0 0]
[ 6 14 24 36]
[     1    128   6561 262144]


In [246]:
print(np.cos(a))
print(np.sin(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


##  Linear Algebra

In [247]:
a = np.full((2, 3), 5)
print(a)

b = np.full((3, 2), 3)
print(b)


print(np.matmul(a, b))

[[5 5 5]
 [5 5 5]]
[[3 3]
 [3 3]
 [3 3]]
[[45 45]
 [45 45]]


In [248]:
#Find the determinent

c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

## Statitics

In [249]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

stats

array([[1, 2, 3],
       [4, 5, 6]])

In [250]:
print(np.min(stats))
print(np.max(stats))
print(np.average(stats))
print(np.sum(stats))
print(np.mean(stats))
print(np.median(stats))
print(np.std(stats))
print(np.var(stats))

1
6
3.5
21
3.5
3.5
1.707825127659933
2.9166666666666665


#### You can do coloum wise and row wise

In [251]:
print(np.min(stats, axis = 0))
print(np.max(stats, axis = 1))
print(np.average(stats, axis = 0))
print(np.sum(stats, axis = 1))
print(np.mean(stats, axis = 0))
print(np.median(stats, axis = 1))
print(np.std(stats, axis = 0))
print(np.var(stats, axis = 1))

[1 2 3]
[3 6]
[2.5 3.5 4.5]
[ 6 15]
[2.5 3.5 4.5]
[2. 5.]
[1.5 1.5 1.5]
[0.66666667 0.66666667]


## Reorganizing arrays

In [252]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

print("-----------------------------------")
print(before.reshape((1, 8)))
print("-----------------------------------")
print(before.reshape((2, 2, 2)))
print("-----------------------------------")

[[1 2 3 4]
 [5 6 7 8]]
-----------------------------------
[[1 2 3 4 5 6 7 8]]
-----------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-----------------------------------


In [253]:
# vertically stacking vectors

v1 = np.array([0, 1, 2, 3])

v2 = np.array([4, 5, 6, 7])


np.vstack([v1, v2, v1, v2, before])

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [254]:
# horizondally stacking vectors

h1 = np.identity(2)

np.hstack([before, h1])

array([[1., 2., 3., 4., 1., 0.],
       [5., 6., 7., 8., 0., 1.]])

## Miscellaneous

#### Load Data from a file
    - we are using the same file Keith Galli
    - we can use pandas, but if you don't want to use pandas

In [255]:
filedata = np.genfromtxt('data.txt',delimiter=',')

In [256]:
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [257]:
filedata_32 = filedata.astype('int32')

In [258]:
print(filedata_32)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean masking  &  Advanced indexing

In [259]:
filedata.shape

(3, 18)

In [260]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [261]:
filedata [filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

## you can index with a list in numpy
    - the index will workout only if it is a boolen value, 0 will not act as boolean
    - False will workout as 0

In [262]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

print(a[[2, 4, 5]])
print(a[[2, 4, 5, False, True]])
#print(a[[ False]])

[1 2 3 4 5 6 7 8 9]
[3 5 6]
[3 5 6 1 2]


In [263]:
np.any(filedata > 50, axis= 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [264]:
np.any(filedata > 50)

True

In [265]:
np.all(filedata > 50, axis= 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [266]:
(filedata > 50) & (filedata <100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [267]:
filedata[(filedata > 50) & (filedata <100)]

array([75., 75., 55., 78., 76., 88.])

In [268]:
filedata[~(filedata > 50) & (filedata <100)]

array([ 1., 13., 21., 11.,  4.,  3., 34.,  6.,  7.,  8.,  0.,  1.,  2.,
        3.,  4.,  5.,  3., 42., 12., 33.,  4.,  6.,  4.,  3.,  4.,  5.,
        6.,  7.,  0., 11., 12.,  1., 22., 33., 11., 11.,  2.,  1.,  0.,
        1.,  2.,  9.,  8.,  7.,  1.])

In [269]:
np.any(filedata[~(filedata > 50) & (filedata <100)], axis = 0)

True

## QR1

1. Inspect
    - ndim, nshape, dtype, itemsize, size, len
    
2. Accessing and Changing different values
    - a[-1, -2], a[1:5:2, 2]
    - a[:, 2] = [9,9]

    - set first element of all arrays
       c[:, :, 0] = 0

    - set the second row in 13, 14, 17, 18
       c[:, 1, :] = [[13, 14],[17, 18]]
			  
    - set the second coumn in 32, 44, 36, 48
       c[:, :, 1] = [[32, 44], [36, 48]]
       
3. Initilizing
    - datatypes, ones, zeros, full, full_like, identity
    - random.rand, random.randint
    - np.ones((2, 3), dtype='int16')
    - p.full_like(test1, 256, dtype='int16')
    - np.random.rand(2, 5)
    - np.random.randint(-4, 5, size=(2, 5))
    - np.repeat(arr, 3, axis=0)
    
4. Copying
    - 3 types, normal, shallow copy, deep copy
    - list3 = list2
    - list3 = list2.copy() #shallow copy
    - list3 = list2[:] #copying by slicing, shallow
    - list3 = copy.deepcopy(list2)
    
5. Mathematics
    - element wise operations
    - arithmetic, power, integer division
    - np.cos(a), np.sin(a)

6. Linear Algebra
    - np.matmul(a, b)
    - np.linalg.det(c)

7. Statitcs
    - stats functions, avg, median, mean, sum, std, var, min, max
    - coloumn wise and row wise operations
    - np.min(stats), np.min(stats, axis = 0)

8. Reorganising arrays
    - np.vstack([v1, v2, v1, v2, before]), np.hstack([before, h1])
        - only requirement is in the direction of stacking elements should match
9. File Load
    - filedata = np.genfromtxt('data.txt',delimiter=',')
    - filedata_32 = filedata.astype('int32')
10. Boolean Masking and advanced indexing
    - filedata is a matrix with numbers
    - filedata_32 = filedata.astype('int32')
    - (filedata > 50) & (filedata <100)
    - filedata[~(filedata > 50) & (filedata <100)]

## QR2

1. numpy is faster than list
2. numpy used fixed type with contigous memory
3. what is negative indexing
4. when you mention a subset of the matrix, it is accessed row wise,
5. you can set multiple elements in a multidimensional matrix, 
    - by assigning a single element,
    - specifying the matrix of right size
6. slicing is exclusive
7. np.repeat(arr, 3, axis=0)
    - axis 0 - row wise
    - axis 1 - column wise
8. copy by slicing is same as shallow copy
9. shallow copy is one level deep
10. a tuple to reshape
10. stats functions are cool
    - min, max, std, var, median, mean
    - and you can do it row or column wise
11. '/' division operation always produces float reuslts
12. Make me a sandwich with 3 matrices
13. you can index with a list in numpy
    - ouput will be a single dimensionl array even if the orginal was 2D array
15. when you load a set of numbers by default it will be floats
16. Slicing is a speicl syntax than lists
        - when you do slicing you index the whole row/coloumn


## QR3


1. why numpy is faster than list?
2. what are the ways to inspect a numpy array?
3. how to know how much memory numpy is taking?
4. can we create a numpy array with full of ones and of dtype 'int16'?
5. what you mean by slicing?
6. what you mean by slicing is exclusing? what we should do in programming to take care of it ?
7. How will you set the 2 element of 2x2x2 matrix in 32, 44, 36, 48 
9. How will you fill a matrix with the same shape as another one very fast?
8. When you pass dimension/shape to intialize a matrix, 
    - what format the dimensions should be
    - how should you specifiy them
9. How will you specify shape to rand function
10. check **practice problem 1**
11. r1  = np.repeat(arr, 3, axis=?) what is the axis is here
12. what is normal copy, shallow copy, and deep copy
13. How to copy by slicing?
14. How will you find the coloum wise maximum/ standard deviation of a matrix?
15. assume you have an array of type 'int32' and divide it by array will the reslt will be int or float?
16. What is the syntax of multiplying two matrices
17. what should be the input to reshape an array,
    - what are the things we have to take care
17. How will you sandwitch 3 matrices

18. a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
        - print(a[[2, 4, 5, False, True]])
        - print(a[[ False]])
        - what will happen in the above two prints
        
19. how to convert a 'float' array to 'int32'?
20. How to select numbers between 50 and 100 in a matrix
21. what will be output of 
    - (filedata > 50) & (filedata <100)?
    - assume file data is 2D array of numbers
    - filedata[(filedata > 50) & (filedata <100)]
22. let test be the array Practice problems - 2
    - what is the output of
        - test[2:4, 0:2 ]
        - test[ [2, 3], [0, 1]]
        
23. check **practice problem 2**



## Practice problems - 1

    - create/initialize the following array effortlessly
    
    [[1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 9, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1]]

In [270]:
 output = np.ones((5, 5))
 print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [271]:
z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [272]:
output[1:4, 1:4] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Practice problems - 2
    - given an input
    - [[1,   2,  3,  4,  5],
       [6,   7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]]
    - How will index 11, 12, 16, 17 ?
    - How will you index 2, 8, 14, 20 ?
    - how will you index [ 4, 5, 24, 25, 29, 30] 

In [273]:
test = np.array(range(1, 31))
print(test)
test = test.reshape((6,5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [274]:
# How will index 11, 12, 16, 17 ?

print(test[2:4, 0:2 ])

print(test[ [2, 3], [0, 1] ])

[[11 12]
 [16 17]]
[11 17]


In [275]:
# How will you index 2, 8, 14, 20 ?

print(test[ [0, 1, 2, 3], [1, 2, 3, 4] ])

[ 2  8 14 20]


In [276]:
# how will you index [ 4, 5, 24, 25, 29, 30] 

print(test[ [0, 4, 5], 3:6])

[[ 4  5]
 [24 25]
 [29 30]]


In [277]:
print(test[ [0, 4, 5], 3:])

[[ 4  5]
 [24 25]
 [29 30]]
